/**
 * Empty template generated by tools/sync_templates.py from SKILL.md.
 * Run main() to create a separate spreadsheet, or buildIntoActive() for unused tabs.
 * Existing target tabs cause an error before any write; no data is deleted or migrated.
 * Do not paste over an existing Apps Script project without preserving its code.
 */
var CONFIG = {
  "title": "Accounting Software Selection",
  "tier": "Growth",
  "layer": "Layer 1: Foundation",
  "fields": [
    {
      "name": "Evaluation ID",
      "type": "text",
      "options": [],
      "example": "",
      "description": ""
    },
    {
      "name": "Software",
      "type": "text",
      "options": [],
      "example": "",
      "description": ""
    },
    {
      "name": "Vendor",
      "type": "text",
      "options": [],
      "example": "",
      "description": ""
    },
    {
      "name": "Business Activities",
      "type": "long_text",
      "options": [],
      "example": "",
      "description": ""
    },
    {
      "name": "Modules Needed",
      "type": "long_text",
      "options": [],
      "example": "",
      "description": ""
    },
    {
      "name": "Deployment Type",
      "type": "select",
      "options": [
        "Cloud",
        "On-premise",
        "Hybrid"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Accounting Coverage",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Sales Support",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Purchase Support",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Inventory Support",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Manufacturing Support",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "BOM Support",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Production/Work Order Support",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Production Costing",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Wastage/Scrap Tracking",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Batch/Lot Tracking",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Service Management",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "VAT Support",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "TDS Support",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Payroll/SSF Support",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "IRD/Statutory Reporting",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "E-Billing/CBMS Support",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Financial Reporting",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Multi-Company Support",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Branch Support",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Warehouse Support",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "User Access Control",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Approval Workflow",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Data Backup & Security",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Migration Support",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Integration/API",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Data Export",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "After-Sales Support",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Implementation Support",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Training",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Customization",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Reliability Rating",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Ease of Use Rating",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Support Quality Rating",
      "type": "select",
      "options": [
        "1 Missing",
        "2 Major limitations",
        "3 Adequate",
        "4 Strong",
        "5 Comprehensive",
        "Not Required",
        "Untested"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Demo Date",
      "type": "date",
      "options": [],
      "example": "",
      "description": ""
    },
    {
      "name": "Demo Test Result",
      "type": "select",
      "options": [
        "Not Tested",
        "Partially Passed",
        "Passed",
        "Failed"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Test Transactions Run",
      "type": "number",
      "options": [],
      "example": "",
      "description": ""
    },
    {
      "name": "Licence Cost",
      "type": "currency",
      "options": [],
      "example": "",
      "description": ""
    },
    {
      "name": "Implementation Cost",
      "type": "currency",
      "options": [],
      "example": "",
      "description": ""
    },
    {
      "name": "Customization Cost",
      "type": "currency",
      "options": [],
      "example": "",
      "description": ""
    },
    {
      "name": "Training Cost",
      "type": "currency",
      "options": [],
      "example": "",
      "description": ""
    },
    {
      "name": "Annual Renewal",
      "type": "currency",
      "options": [],
      "example": "",
      "description": ""
    },
    {
      "name": "First-Year Cost",
      "type": "currency",
      "options": [],
      "example": "",
      "description": ""
    },
    {
      "name": "Three-Year TCO",
      "type": "currency",
      "options": [],
      "example": "",
      "description": ""
    },
    {
      "name": "Evaluation Status",
      "type": "select",
      "options": [
        "Not Evaluated",
        "Demo Scheduled",
        "Demo Completed",
        "Testing",
        "Evaluated"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Deal-breaker",
      "type": "select",
      "options": [
        "Yes",
        "No",
        "Unknown"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Selection Decision",
      "type": "select",
      "options": [
        "Selected",
        "Shortlisted",
        "Not Selected",
        "Rejected"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Rejection Reason",
      "type": "select",
      "options": [
        "Cost",
        "Missing Capability",
        "Poor Fit",
        "Poor Support",
        "Implementation Risk",
        "Security Risk",
        "User Experience",
        "Other"
      ],
      "example": "",
      "description": ""
    },
    {
      "name": "Evaluated By",
      "type": "text",
      "options": [],
      "example": "",
      "description": ""
    },
    {
      "name": "Evidence/Source",
      "type": "text",
      "options": [],
      "example": "",
      "description": ""
    },
    {
      "name": "Notes",
      "type": "long_text",
      "options": [],
      "example": "",
      "description": ""
    },
    {
      "name": "Selection ID",
      "type": "id",
      "options": [],
      "example": "",
      "description": ""
    }
  ],
  "example": [],
  "optionsSheet": "Options",
  "referenceSheet": "Field Reference",
  "infoSheet": "About",
  "dataSheet": "Accounting Software Selection",
  "generated": [
    "Accounting Software Selection",
    "Options",
    "Field Reference",
    "About"
  ],
  "dataRows": 500,
  "rowEntity": "",
  "lastReviewed": "2026-09-26",
  "source": "SME Ops System Builder",
  "limitations": [
    "Empty template only. It does not score for you, run the demos, verify a vendor's claims or turn a quotation into a TCO.",
    "It never selects the package. It records the decision the business makes in Selection Decision, with the reason and the deal-breaker flag beside it; it does not make the decision.",
    "Not a bookkeeping, tax-filing, legal or procurement system. Quotations, contracts and purchase orders stay in the vendor's own process.",
    "It cannot verify Nepal IRD, VAT, TDS, e-billing, CBMS or SSF handling for you. Those stay Untested until the business holds current evidence from the vendor or the authority.",
    "A go-live checklist is a list the business carries out with the vendor. Chart of accounts, tax configuration, users, inventory, opening balances and the test entry are not done by this skill.",
    "Notion relations need both databases imported before the link column resolves."
  ]
};

var HEADER_BG = '#1F3864';
var INFO_BG = '#E8EDF5';
var DEFAULT_WIDTH = 150;
var WIDE_WIDTH = 220;
var WRAP_WIDTH = 300;
var NUMFORMATS = {
  text: '@', id: '@', relation: '@', email: '@', phone: '@', url: '@',
  date: 'yyyy-mm-dd', datetime: 'yyyy-mm-dd hh:mm',
  currency: '#,##0.00', number: '#,##0.##', percentage: '0.##'
};

/** Adds the menu, when this script is bound to a spreadsheet. */
function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('Build template')
    .addItem('Build into unused tabs', 'buildIntoActive')
    .addToUi();
}

/** Creates a new spreadsheet and builds the template into it. */
function main() {
  var ss = SpreadsheetApp.create(CONFIG.title);
  build(ss);
  Logger.log('Created ' + ss.getUrl());
  return ss.getUrl();
}

/** Builds the template into the spreadsheet this script is bound to. */
function buildIntoActive() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  build(ss);
  SpreadsheetApp.getUi().alert(
    'Template created: ' + CONFIG.dataSheet + ', ' +
    CONFIG.fields.length + ' columns.');
}

/** Fail before any mutation if a target tab already exists. */
function assertUnusedSheets(ss) {
  var names = [CONFIG.dataSheet, CONFIG.optionsSheet, CONFIG.referenceSheet, CONFIG.infoSheet];
  if (new Set(names).size !== names.length) throw new Error('Template tab names must be unique.');
  var conflicts = names.filter(function (name) { return ss.getSheetByName(name); });
  if (conflicts.length) {
    throw new Error('Existing tabs left unchanged: ' + conflicts.join(', ') +
      '. Use main() to create a separate spreadsheet.');
  }
}

/** A new tab with enough capacity for the complete template. */
function freshSheet(ss, name) {
  var sheet = ss.insertSheet(name);
  var columns = Math.max(CONFIG.fields.length, 6);
  var optionRows = CONFIG.fields.reduce(function (max, f) {
    return Math.max(max, (f.options || []).length + 1);
  }, 1);
  var rows = Math.max(CONFIG.dataRows + 1, CONFIG.fields.length + 1,
    CONFIG.limitations.length + 12, optionRows);
  if (sheet.getMaxColumns() < columns) {
    sheet.insertColumnsAfter(sheet.getMaxColumns(), columns - sheet.getMaxColumns());
  }
  if (sheet.getMaxRows() < rows) {
    sheet.insertRowsAfter(sheet.getMaxRows(), rows - sheet.getMaxRows());
  }
  return sheet;
}

/** Literal strings from a specification must not become executable formulas. */
function literal(value) {
  return typeof value === 'string' && /^[\s]*[=+@-]/.test(value) ? "'" + value : value;
}

/** Writes a row of values starting at A1 of the given row. */
function writeRow(sheet, row, values) {
  values.forEach(function (value, i) {
    sheet.getRange(row, i + 1).setValue(value === null ? '' : literal(value));
  });
}

/** Applies the dropdown for one select field. */
function applySelectRule(ss, sheet, column, field) {
  if (!field.options || !field.options.length) return;
  var options = ss.getSheetByName(CONFIG.optionsSheet);
  if (!options) return;
  var selects = CONFIG.fields.filter(function (f) {
    return f.type === 'select' && f.options && f.options.length;
  });
  var optionColumn = selects.findIndex(function (f) { return f.name === field.name; }) + 1;
  var rule = SpreadsheetApp.newDataValidation()
    .requireValueInRange(options.getRange(2, optionColumn, field.options.length, 1), true)
    .setAllowInvalid(true)
    .setHelpText('Suggested options; adapt to the confirmed business taxonomy.')
    .build();
  sheet.getRange(2, column, CONFIG.dataRows, 1).setDataValidation(rule);
}

/** Applies the Yes/No dropdown for one checkbox column. */
function applyCheckboxRule(sheet, column) {
  var rule = SpreadsheetApp.newDataValidation()
    .requireValueInList(["Yes", "No"], true)
    .setAllowInvalid(false)
    .setHelpText('Yes or No.')
    .build();
  sheet.getRange(2, column, CONFIG.dataRows, 1).setDataValidation(rule);
}

/** The Options tab: one column per select field, so rules can point at it. */
function buildOptionsSheet(ss) {
  var selects = CONFIG.fields.filter(function (f) {
    return f.type === 'select' && f.options && f.options.length;
  });
  if (!selects.length) return null;

  var sheet = freshSheet(ss, CONFIG.optionsSheet);
  writeRow(sheet, 1, selects.map(function (f) { return f.name; }));
  selects.forEach(function (f, i) {
    var values = f.options.map(function (o) { return [literal(o)]; });
    if (values.length) {
      sheet.getRange(2, i + 1, values.length, 1).setValues(values);
    }
    sheet.setColumnWidth(i + 1, 180);
  });
  styleHeader(sheet, 1, selects.length);
  return sheet;
}

/** The Field Reference tab: what every column is for. */
function buildReferenceSheet(ss) {
  var sheet = freshSheet(ss, CONFIG.referenceSheet);
  var head = ['#', 'Field', 'Type', 'Options', 'Example', 'Description'];
  writeRow(sheet, 1, head);
  CONFIG.fields.forEach(function (f, i) {
    writeRow(sheet, i + 2, [
      i + 1,
      f.name,
      f.type,
      f.options && f.options.length ? f.options.join(', ') : '',
      f.example === null ? '' : f.example,
      f.description || ''
    ]);
  });
  var last = CONFIG.fields.length + 1;
  sheet.getRange(2, 1, last - 1, 6).setVerticalAlignment('top');
  sheet.getRange(2, 6, last - 1, 1).setWrap(true);
  sheet.setColumnWidth(1, 40);
  sheet.setColumnWidth(2, 260);
  sheet.setColumnWidth(3, 90);
  sheet.setColumnWidth(4, 260);
  sheet.setColumnWidth(5, 260);
  sheet.setColumnWidth(6, 320);
  styleHeader(sheet, 1, head.length);
  sheet.setFrozenRows(1);
  return sheet;
}

/** The Info tab: what this template is, and what it will not do. */
function buildInfoSheet(ss) {
  var sheet = freshSheet(ss, CONFIG.infoSheet);
  var rows = [
    ['Module', CONFIG.title],
    ['Tier', CONFIG.tier],
    ['Layer', CONFIG.layer],
    ['Fields', CONFIG.fields.length],
    ['One row is', CONFIG.rowEntity],
    ['Last reviewed', CONFIG.lastReviewed],
    ['Source', CONFIG.source]
  ];
  writeRow(sheet, 1, ['What this is', '']);
  rows.forEach(function (r, i) {
    writeRow(sheet, i + 2, r);
  });
  sheet.getRange(1, 1, 1, 2).setBackground(INFO_BG).setFontWeight('bold');

  var limitRow = rows.length + 3;
  writeRow(sheet, limitRow, ['What this does not do', '']);
  sheet.getRange(limitRow, 1, 1, 2).setBackground(INFO_BG).setFontWeight('bold');
  CONFIG.limitations.forEach(function (text, i) {
    writeRow(sheet, limitRow + 1 + i, ['-', text]);
    sheet.getRange(limitRow + 1 + i, 2).setWrap(true);
  });

  sheet.setColumnWidth(1, 150);
  sheet.setColumnWidth(2, 320);
  sheet.getRange(1, 1, limitRow + CONFIG.limitations.length, 2)
    .setVerticalAlignment('top');
  return sheet;
}

/** Bold white-on-navy, which is what makes a header row read as a header. */
function styleHeader(sheet, row, columns) {
  var range = sheet.getRange(row, 1, 1, columns);
  range.setBackground(HEADER_BG)
    .setFontColor('#ffffff')
    .setFontWeight('bold')
    .setVerticalAlignment('bottom')
    .setWrap(true);
  sheet.setRowHeight(row, 30);
}

/** Builds new tabs only. Repeated calls fail without changing existing tabs. */
function build(ss) {
  assertUnusedSheets(ss);
  buildOptionsSheet(ss);

  var data = freshSheet(ss, CONFIG.dataSheet);
  var names = CONFIG.fields.map(function (f) { return f.name; });
  writeRow(data, 1, names);
  styleHeader(data, 1, names.length);
  data.setFrozenRows(1);

  CONFIG.fields.forEach(function (f, i) {
    var column = i + 1;
    var format = NUMFORMATS[f.type];
    if (format) {
      data.getRange(2, column, CONFIG.dataRows, 1).setNumberFormat(format);
    }
    if (f.type === 'long_text') {
      data.getRange(2, column, CONFIG.dataRows, 1).setWrap(true);
      data.setColumnWidth(column, WRAP_WIDTH);
    } else if (names[i].length > 18) {
      data.setColumnWidth(column, WIDE_WIDTH);
    } else {
      data.setColumnWidth(column, DEFAULT_WIDTH);
    }
    if (f.type === 'select') applySelectRule(ss, data, column, f);
    if (f.type === 'checkbox') applyCheckboxRule(data, column);
  });

  if (names.length) {
    data.getRange(1, 1, 1, names.length).createFilter();
  }
  buildReferenceSheet(ss);
  buildInfoSheet(ss);
  return ss;
}
